#!/usr/bin/python

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
from pyakm.kernel_module import *
from pyakm.gui_manager import *
import sys, re

class MainApp:

    def __init__(self):

        self.builder = Gtk.Builder()
        self.builder.add_from_file("/usr/share/pyakm/ui/manager.ui")
        self.window = self.builder.get_object("window1")

        self.kernel_name = sys.argv[1]
        
        self.packages = grab_kernel_packages_by_name(kernel_name)
        self.packages = sort_and_filter_packages(kernel_name, packages)

        self.treeview = create_treeview1(builder)
        self.liststore = populate_list_store_from_packages(packages, kernel_name)
        self.treeview.set_model(liststore)

        self.select = treeview.get_selection()
        self.select.connect("changed", Handler.on_tree_selection_changed)
        
        
    def on_tree_selection_changed(self,selection):
        model, treeiter = selection.get_selected()
        if treeiter != None:
            print("You selected", model[treeiter][0],
                  model[treeiter][1], model[treeiter][2])

app = MainApp()
app.window.connect("delete-event", Gtk.main_quit)
app.window.show_all()
Gtk.main()
