#!/usr/bin/python

from pyakm.kernel_module import *
from pyakm.grub_config import *
import sys

if not (len(sys.argv) == 2):
    print('Usage: pyakm-select-default [kernel]')
    exit(1)

kernel_name = sys.argv[1]
kernel_id = kernel_dicts[kernel_name]
    
kernel_list = grab_kernel_official()
print('Kernel %s will default in grub --> \n' % kernel_name)


replace_grub_str(kernel_list[kernel_id])