#!/usr/bin/python

from pyakm.kernel_module import *
import sys

if not (len(sys.argv) == 2):
    print('Usage: pyakm-remove-kernel [kernel]')
    exit(1)

kernel_name = sys.argv[1]
kernel_id = kernel_dicts[kernel_name]
    
kernel_list = grab_kernel_official()
print('Current status of %s --> \n' % kernel_name)

remove_kernel(kernel_list[kernel_id])
